#User defined
user:
  WP_version:
    label:
      WordPress version
    hint:
      Select WordPress version
    type:
      select
    values:
      - "6.8"
      - "6.7"
      - "6.6"
      - "6.5"
      - "6.4"
      - "6.3"
      - "6.2"
      - "6.1"
      - "6.0"
      - "5.9"
      - "4.9"
    target:
      WORDPRESS_VERSION

  wp_debug:
    label:
      Enable WordPress debug mode?
    hint:
      Check to enable WordPress debug mode
    type:
      checkbox
    target:
      WORDPRESS_DEBUG

  wp_db_host:
    label:
      Database host
    hint:
      The host name of your database (MySQL or MariaDB)
    type:
      text-input
    target:
      DB_HOST

#System defaults
system:
  show_localpath_selector:
    true
  db_credentials:
    true
    
  #Generate public ports for the docker image
  ports:
    http:
      WP_HTTP_PORT
    others:
      - PMA_PORT